---
- :id: address-book
  :unicode: f2b9
- :id: address-card
  :unicode: f2bb
- :id: angry
  :unicode: f556
- :id: arrow-alt-circle-down
  :unicode: f358
- :id: arrow-alt-circle-left
  :unicode: f359
- :id: arrow-alt-circle-right
  :unicode: f35a
- :id: arrow-alt-circle-up
  :unicode: f35b
- :id: bell
  :unicode: f0f3
- :id: bell-slash
  :unicode: f1f6
- :id: bookmark
  :unicode: f02e
- :id: building
  :unicode: f1ad
- :id: calendar
  :unicode: f133
- :id: calendar-alt
  :unicode: f073
- :id: calendar-check
  :unicode: f274
- :id: calendar-minus
  :unicode: f272
- :id: calendar-plus
  :unicode: f271
- :id: calendar-times
  :unicode: f273
- :id: caret-square-down
  :unicode: f150
- :id: caret-square-left
  :unicode: f191
- :id: caret-square-right
  :unicode: f152
- :id: caret-square-up
  :unicode: f151
- :id: chart-bar
  :unicode: f080
- :id: check-circle
  :unicode: f058
- :id: check-square
  :unicode: f14a
- :id: circle
  :unicode: f111
- :id: clipboard
  :unicode: f328
- :id: clock
  :unicode: f017
- :id: clone
  :unicode: f24d
- :id: closed-captioning
  :unicode: f20a
- :id: comment
  :unicode: f075
- :id: comment-alt
  :unicode: f27a
- :id: comment-dots
  :unicode: f4ad
- :id: comments
  :unicode: f086
- :id: compass
  :unicode: f14e
- :id: copy
  :unicode: f0c5
- :id: copyright
  :unicode: f1f9
- :id: credit-card
  :unicode: f09d
- :id: dizzy
  :unicode: f567
- :id: dot-circle
  :unicode: f192
- :id: edit
  :unicode: f044
- :id: envelope
  :unicode: f0e0
- :id: envelope-open
  :unicode: f2b6
- :id: eye
  :unicode: f06e
- :id: eye-slash
  :unicode: f070
- :id: file
  :unicode: f15b
- :id: file-alt
  :unicode: f15c
- :id: file-archive
  :unicode: f1c6
- :id: file-audio
  :unicode: f1c7
- :id: file-code
  :unicode: f1c9
- :id: file-excel
  :unicode: f1c3
- :id: file-image
  :unicode: f1c5
- :id: file-pdf
  :unicode: f1c1
- :id: file-powerpoint
  :unicode: f1c4
- :id: file-video
  :unicode: f1c8
- :id: file-word
  :unicode: f1c2
- :id: flag
  :unicode: f024
- :id: flushed
  :unicode: f579
- :id: folder
  :unicode: f07b
- :id: folder-open
  :unicode: f07c
- :id: frown
  :unicode: f119
- :id: frown-open
  :unicode: f57a
- :id: futbol
  :unicode: f1e3
- :id: gem
  :unicode: f3a5
- :id: grimace
  :unicode: f57f
- :id: grin
  :unicode: f580
- :id: grin-alt
  :unicode: f581
- :id: grin-beam
  :unicode: f582
- :id: grin-beam-sweat
  :unicode: f583
- :id: grin-hearts
  :unicode: f584
- :id: grin-squint
  :unicode: f585
- :id: grin-squint-tears
  :unicode: f586
- :id: grin-stars
  :unicode: f587
- :id: grin-tears
  :unicode: f588
- :id: grin-tongue
  :unicode: f589
- :id: grin-tongue-squint
  :unicode: f58a
- :id: grin-tongue-wink
  :unicode: f58b
- :id: grin-wink
  :unicode: f58c
- :id: hand-lizard
  :unicode: f258
- :id: hand-paper
  :unicode: f256
- :id: hand-peace
  :unicode: f25b
- :id: hand-point-down
  :unicode: f0a7
- :id: hand-point-left
  :unicode: f0a5
- :id: hand-point-right
  :unicode: f0a4
- :id: hand-point-up
  :unicode: f0a6
- :id: hand-pointer
  :unicode: f25a
- :id: hand-rock
  :unicode: f255
- :id: hand-scissors
  :unicode: f257
- :id: hand-spock
  :unicode: f259
- :id: handshake
  :unicode: f2b5
- :id: hdd
  :unicode: f0a0
- :id: heart
  :unicode: f004
- :id: hospital
  :unicode: f0f8
- :id: hourglass
  :unicode: f254
- :id: id-badge
  :unicode: f2c1
- :id: id-card
  :unicode: f2c2
- :id: image
  :unicode: f03e
- :id: images
  :unicode: f302
- :id: keyboard
  :unicode: f11c
- :id: kiss
  :unicode: f596
- :id: kiss-beam
  :unicode: f597
- :id: kiss-wink-heart
  :unicode: f598
- :id: laugh
  :unicode: f599
- :id: laugh-beam
  :unicode: f59a
- :id: laugh-squint
  :unicode: f59b
- :id: laugh-wink
  :unicode: f59c
- :id: lemon
  :unicode: f094
- :id: life-ring
  :unicode: f1cd
- :id: lightbulb
  :unicode: f0eb
- :id: list-alt
  :unicode: f022
- :id: map
  :unicode: f279
- :id: meh
  :unicode: f11a
- :id: meh-blank
  :unicode: f5a4
- :id: meh-rolling-eyes
  :unicode: f5a5
- :id: minus-square
  :unicode: f146
- :id: money-bill-alt
  :unicode: f3d1
- :id: moon
  :unicode: f186
- :id: newspaper
  :unicode: f1ea
- :id: object-group
  :unicode: f247
- :id: object-ungroup
  :unicode: f248
- :id: paper-plane
  :unicode: f1d8
- :id: pause-circle
  :unicode: f28b
- :id: play-circle
  :unicode: f144
- :id: plus-square
  :unicode: f0fe
- :id: question-circle
  :unicode: f059
- :id: registered
  :unicode: f25d
- :id: sad-cry
  :unicode: f5b3
- :id: sad-tear
  :unicode: f5b4
- :id: save
  :unicode: f0c7
- :id: share-square
  :unicode: f14d
- :id: smile
  :unicode: f118
- :id: smile-beam
  :unicode: f5b8
- :id: smile-wink
  :unicode: f4da
- :id: snowflake
  :unicode: f2dc
- :id: square
  :unicode: f0c8
- :id: star
  :unicode: f005
- :id: star-half
  :unicode: f089
- :id: sticky-note
  :unicode: f249
- :id: stop-circle
  :unicode: f28d
- :id: sun
  :unicode: f185
- :id: surprise
  :unicode: f5c2
- :id: thumbs-down
  :unicode: f165
- :id: thumbs-up
  :unicode: f164
- :id: times-circle
  :unicode: f057
- :id: tired
  :unicode: f5c8
- :id: trash-alt
  :unicode: f2ed
- :id: user
  :unicode: f007
- :id: user-circle
  :unicode: f2bd
- :id: window-close
  :unicode: f410
- :id: window-maximize
  :unicode: f2d0
- :id: window-minimize
  :unicode: f2d1
- :id: window-restore
  :unicode: f2d2
